sudo: required
services:
  - docker

before_install:
  - docker build -t satyamj/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true satyamj/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockerreact"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-034366228295"
  bucker_path: "dockerreact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
